services:

  postgres:
    image: "postgres:${POSTGRES_VERSION:-17.0-bookworm}"
    restart: always
    volumes:
      - $HOME/MobSF/postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/mobsfDB_password
      - POSTGRES_DB=mobsf
    networks:
      - mobsf_network
    secrets:
      - mobsfDB_password

  mobsf:
    build:
      context: https://github.com/mishanad07/SPeTMA.git  # Your GitHub repository URL
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
      - "1337:1337"
    volumes:
      - $HOME/MobSF/mobsf_data:/home/mobsf/.MobSF
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/mobsfDB_password
      - POSTGRES_DB=mobsf
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MOBSF_API_KEY_FILE=/run/secrets/mobsf_api_key
    healthcheck:
      test: curl -f http://localhost:8000/login/ || exit 1
    depends_on:
      - postgres
    networks:
      - mobsf_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - mobsfDB_password
      - mobsf_api_key

  nginx:
    image: nginx:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    ports:
      - "80:4000"
      - "1337:4001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mobsf
    networks:
      - mobsf_network

  djangoq:
    build:
      context: https://github.com/mishanad07/SPeTMA.git  # Your GitHub repository URL
      dockerfile: Dockerfile
    restart: unless-stopped
    command: /home/mobsf/Mobile-Security-Framework-MobSF/scripts/qcluster.sh
    volumes:
      - $HOME/MobSF/mobsf_data:/home/mobsf/.MobSF
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/mobsfDB_password
      - POSTGRES_DB=mobsf
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    networks:
      - mobsf_network

networks:
  mobsf_network:
    driver: overlay

secrets:
  mobsfDB_password:
    external: true
  mobsf_api_key:
    external: true
